dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
- python setup.py install
script: pytest
addons:
  ssh_known_hosts:
  - 3.19.73.149
before_deploy:
  - openssl aes-256-cbc -K $encrypted_49099c38b3b5_key -iv $encrypted_49099c38b3b5_iv -in deploy_rsa.enc -out deploy_rsa -d
  - chmod 600 deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i deploy_rsa ubuntu@18.219.192.252 'source /home/ubuntu/CICD_Practice/deploy.sh'
